### ISSUE TITLE
'SPACE_SHOOTER_MIN_FRAME_TIME' is undeclared identifier

### ISSUE THREAD

**Issue by longtran2904** [tsherif/space-shooter.c#10]
The `windows.c` needs `SPACE_SHOOTER_MIN_FRAME_TIME` but the `constants.h` define it as `SPACE_SHOOTER_MIN_FRAME_TIME_NS`. I also tried to remove the `_NS` part but then the game just freeze. After looking through the startup code, I saw this:
```
        if (useSleep && SPACE_SHOOTER_MIN_FRAME_TIME - elapsedTime > 1.0f) {
            DWORD sleepMs = (DWORD) (SPACE_SHOOTER_MIN_FRAME_TIME - elapsedTime);
            Sleep(sleepMs);
```
The `sleepMs` was a very high number. If I replace the macro with something else like `1/60` then it would work just fine.

**Comment by tsherif** [comment]
If you pull the latest commits, this should be fixed. The Windows build was broken for one commit this morning (2f3be4e330b085a106fb15e491e911d3dc6c76bd) while I was doing some refactoring.

**Comment by longtran2904** [comment]
Yep! It has been fixed!
