### ISSUE TITLE
Issue compiling on Windows - error C2220 and warning C4204

### ISSUE THREAD

**Issue by mawaldne** [tsherif/space-shooter.c#14]
Hi Tarek, thank you for making this project!

For anyone trying to compile this project on windows (Windows 10 Home for me), I ran into a slight problem. After running build.bat in a shell with cl setup, I got an error:

```
....
..\src\game\entities.c(135): error C2220: the following warning is treated as an error
..\src\game\entities.c(135): warning C4204: nonstandard extension used: non-constant aggregate initializer
...More of these warnings...
```

The way I solved this for now was to remove the /WX compile option from the build.bat script (basically replace line 8 with the line below):

```
@set shared_args=/std:c11 /W4 /wd5105 /wd4201 /wd4100 /D SOGL_MAJOR_VERSION=3 /D SOGL_MINOR_VERSION=3 /Fespace-shooter
```

/WX tells the compiler to treat all warnings as errors, so this probably isn't the best solution! But it's a workaround for now. Im not a C/C++ dev so not sure how to solve "non-constant aggregate initializer".  If I figure it out I will post here.

**Comment by tsherif** [comment]
Thanks for reporting this @mawaldne. Can you tell me what version of MSVC you're using? I don't get those errors when I compile with MSVC 2019 Community Edition.

Warning [C4204](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4204?view=msvc-170) is related to the fact that I initialize those "argument" structs with non-constant values, but it looks like that should only be emitted when the [ANSI compatibility flag (/Za)](https://docs.microsoft.com/en-us/cpp/build/reference/za-ze-disable-language-extensions?view=msvc-160) is set. I believe this behavior is valid in C11, but I'll double check that.

If you explicitly enable MS extensions by adding the `/Ze` flag to the `shared_args` does it work?

**Comment by mawaldne** [comment]
I figured it out. I was on an older version of Visual Studio Community Edition. I went from 16.4.2 -> 16.11.8 and that seemed to fix the problem. Compiles on Windows now with no issues. 

Thank you!

**Comment by tsherif** [comment]
Great! Thanks for letting me know.
